AWSTemplateFormatVersion: '2010-09-09'
Description: Create an RDS MySQL instance in an existing VPC.

Parameters:
  VPCId:
    Type: String
    Description: The ID of the existing VPC.
  SubnetIds:
    Type: CommaDelimitedList
    Description: Comma-separated list of subnet IDs in the VPC.

Resources:
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to RDS instance
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0  # Adjust for production environments

  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds: !Ref SubnetIds

  MyRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: inventorydb
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: mysql
      MasterUsername: admin
      MasterUserPassword: adminpassword123
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !GetAtt RDSSecurityGroup.GroupId
      DBSubnetGroupName: !Ref RDSSubnetGroup

Outputs:
  RDSInstanceEndpoint:
    Description: The connection endpoint for the RDS database.
    Value: !GetAtt MyRDSInstance.Endpoint.Address
