name: Deploy App to AWS AppRunner

on:
  push:
    branches:
      - main

jobs:
  deploy-app-runner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Native docker ECR login
      id: docker-ecr-login
      run: |
        result=$(aws ecr get-login-password --region | docker login --username AWS --password-stdin 381492212823.dkr.ecr.us-east-2.amazonaws.com)
        echo "Login Result: $result"

    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      run: |
        docker build -t flask-app-tarsl .
        docker tag flask-app-tarsl:latest 381492212823.dkr.ecr.us-east-2.amazonaws.com/flask-app-tarsl:latest
        docker push 381492212823.dkr.ecr.us-east-2.amazonaws.com/flask-app-tarsl:latest